name: Auto Release

on:
  push:
    branches:
      - main

jobs:
  tag_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Tag
        id: create_tag
        run: |
          VERSION=$(date +'%Y%m%d-%H%M')
          git tag "v${VERSION}"
          git push origin "v${VERSION}"
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          name: "Release ${{ steps.create_tag.outputs.version }}"
          draft: false
          prerelease: false
